config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get '/notes/week', to: 'notes#week'
  get '/notes/month', to: 'notes#month'
  get '/habits/month', to: 'habits#month'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :notes
  resources :habits
  get '/login', to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, uniqueness: true
    has_many :notes, dependent: :destroy
    has_many :habits, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
    before_action :authorize
    
    def index
        @habits = current_user.habits
    end

    def show
        @habit = Habit.find(params[:id])
    end

    def new
        @habit = Habit.new
    end

    def create
        @habit = Habit.new
        @habit.user = current_user
        @habit.name = params[:name]
        @habit.color = params[:colors]
        @habit.dates = params[:day_complete]
        if @habit.save
            redirect_to @habit, notice: 'habit was successfully created.'
        else
            render :new
        end
    end

    def destroy
        @habit = Habit.find(params[:id])
        @habit.destroy
        flash[:notice] = "habit deleted"
        redirect_to habits_path
    end

    def edit
        @habit = Habit.find(params[:id])
    end

    def update
        @habit = Habit.find(params[:id])
        @habit.name = params[:name]
        @habit.dates = params[:day_complete]
        if @habit.update_attributes(habit_params)
            redirect_to habits_path
        else
            render :edit
        end
    end

    def week
        @habits = current_user.habits
    end
    
    def month
        @habits = current_user.habits
    end

    private

    def habit_params
        params.require(:habit).permit(:name, :color)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authorize
    
    def index
        @notes = current_user.notes
    end

    def show
        @note = Note.find(params[:id])
    end

    def new
        @note = Note.new
    end

    def create
        @note = Note.new(note_params)
        dt = params[:due_date]
        @note.complete = params[:complete]
        @note.due = Time.new(dt[:year], dt[:month], dt[:day])
        @note.user = current_user
        if @note.save
            redirect_to @note, notice: 'Note was successfully created.'
        else
            render :new
        end
    end

    def destroy
        @note = Note.find(params[:id])
        @note.destroy
        flash[:notice] = "Note deleted"
        redirect_to notes_path
    end

    def edit
        @note = Note.find(params[:id])
    end

    def update
        @note = Note.find(params[:id])
        dt = params[:due_date]
        @note.due = Time.new(dt[:year], dt[:month], dt[:day])
        @note.complete = params[:complete]
        if @note.update_attributes(note_params)
            redirect_to notes_path
        else
            render :edit
        end
    end

    def week
        @notes = current_user.notes
    end
    
    def month
        @notes = current_user.notes
    end

    private

    def note_params
        params.require(:note).permit(:content, :note_type)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
      def new
      end
    
      def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to notes_path, notice: 'Logged in!'
        else
          flash.now.alert = 'Invalid login credentials - try again!'
          render :new
        end
      end
    
      def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
      end
    
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "You have successfully signed up!"
        redirect_to root_path
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/habits/edit.html.erb
<div class="new">
    <h2><%=@habit.name%></h2>
    <%= form_for @habit do |f| %>
            <%= f.label 'Habit' %>
            <%= f.text_field(:name)%>
    <div class="editMonth">
        <%= month_calendar number_of_weeks: 1 do |date| %>
            <%= date.day %>
            <% if @habit.dates %>
                <%=check_box_tag('day_complete[]', date, checked = @habit.dates.include?(date))%>
            <% else %>
                <%=check_box_tag('day_complete[]', date)%>
            <% end %>
        <% end %>
    </div>
    <%= f.submit "Update", class: 'btn btn-success' %>
    <% end %>
</div>

app/views/habits/index.html.erb
<div class="index">
    <h2>All Habits</h2>
    <ul class="habit-list">
        <% @habits.each do |habit| %>
            <li>
                <span>
                    <div class="box" id="<%=habit.color%>"></div>
                    <%= link_to habit.name, habit_path(habit) %>
                </span>
            </li>
        <%end%>
    </ul>
    <%= link_to 'New Habit', new_habit_path %>
</div>

app/views/habits/month.html.erb
<div class="left-bar">
    <ul class="habit-list">
        <% @habits.each do |habit| %>
            <li>
                <div class="box" id="<%=habit.color%>"></div>
                <%= link_to habit.name, edit_habit_path(habit) %>
            </li>
        <%end%>
    </ul>
</div>
<div class="habitMonth">
    <%= month_calendar do |date|%>
        <%= date.day %>
        <% @habits.each do |habit|%>
            <% if habit.dates %>
                <% habit.dates.each do |hd| %>
                    <% if hd == date %>
                        <div class="box" id="<%=habit.color%>"></div>
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
</div>

app/views/habits/new.html.erb
<h2 class="new">New Habit</h2>

<%= form_for @habit do |f| %>
    <div class="new">
        <%= f.label 'Habit' %>
        <input type="text" name="name">
    </div>
    <div class="new">
        <select name="colors">
            <option value="red">Red</option>
            <option value="blue">Blue</option>
            <option value="orange">Orange</option>
            <option value="yellow">Yellow</option>
            <option value="green">Green</option>
            <option value="purple">Purple</option>
        </select>
    </div>
    <div class="editMonth">
        <%= month_calendar number_of_weeks: 1 do |date| %>
            <%= date.day %>
            <%=check_box_tag('day_complete[]', date, checked = @habit.dates.include?(date))%>
        <% end %>
    </div>
    <span class="new"><%= f.submit "Add", class: 'btn btn-success' %></span>
<% end %>

app/views/habits/show.html.erb
<div class="new">
    <h2><%= @habit.name %></h2>
    <div class="box <%= @habit.color %>"></div>
    <br><br>
    <%= link_to "Habits", habits_path, class: 'btn btn-default' %>
    <%= link_to "Edit", edit_habit_path(@habit), class: 'btn btn-primary'%>
    <%= link_to "Delete", habit_path(@habit), method: :delete, data: {confirm: "Are you sure you want to delete this habit?"}, class: 'btn btn-danger'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BulletJournal</title>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- jQuery below -->
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js' %>

    <!-- Bootstrap below -->
    <%= stylesheet_link_tag  'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>

    <!-- custom JS and CSS below -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class ="container header">
      <p>
        <% if current_user %>
          &nbsp;&nbsp;&nbsp;&nbsp;
          Welcome, <%= current_user.name %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to "New Note", new_note_path%>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to "To Do", notes_path%>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to "Week", note_path('week')%>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to "Month", note_path('month')%>
        <% else %>
          <%= link_to 'Log In', login_path %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Sign Up', new_user_path %>
        <% end %>
      </p>
    </div>
    <%if current_user%>
      <div class="sidebar">
        <ul>
            <li><%= link_to 'Habit Tracker', habit_path('month') %></li>
            <li><%= link_to 'All Habits', habits_path %></li>
            <li><%= link_to 'New Habit', new_habit_path %></li>
        </ul>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<div class="new">
    <h2>Edit Note</h2>

    <%= form_for @note do |f| %>
        <div>
            <%= f.text_field :content %>
        </div>
        <div>
            <%= f.radio_button :note_type, "task" %>
            <%= label :note_type_task, "Task" %>
            <%= f.radio_button :note_type, "event" %>
            <%= label :note_type_event, "Event" %>
            <%= f.radio_button :note_type, "note" %>
            <%= label :note_type_note, "Note" %>
        </div>
        <div>
            Due:
            <%= select_date Date.today, prefix: :due_date %>
        </div>
        <div>
            <%= check_box_tag :complete %>
            <%= label_tag(:complete, "Complete") %>
        </div>
        <%= f.submit "Update", class: "btn btn-success"%>
    <% end %>
    <%= link_to "Back", notes_path %>
</div>

app/views/notes/index.html.erb
<div class="index">
    <h2>To Do</h2>
    <div class="notice"><%= flash[:notice] %></div>
    <ul class="notes">
        <% @notes.each do |note| %>
            <% if !note.complete %>
                <li class="<%= note.note_type %>">
                    <span class="<%=note.complete%>">
                    <%= link_to note.content, note_path(note) %>
                    <% if note.due %>
                    <%= note.due.month %>/<%= note.due.day%>
                    </span>
                    <% end %> 
                <% end %>
            </li>
        <%end%>
    </ul>
</div>

app/views/notes/month.html.erb
<div class="month">
    <%= month_calendar do |date| %>
        <strong><%= date.day %></strong>
        <p>
            <%@notes.each do |note|%>
                <span class="<%=note.complete%>">
                <%if note.due.year == date.year && note.due.month == date.month && note.due.day == date.day%>
                <%= link_to note.content, note_path(note) %>
                </span>
            <% end %>
        </p>
        <% end %>
    <% end %>
</div>

app/views/notes/new.html.erb
<div class="new">
    <h2>New Note</h2>

    <%= form_for @note do |f| %>
        <div>
            <%= f.text_field :content %>
        </div>
        <div>
            <%= f.radio_button :note_type, "task" %>
            <%= label :note_type_task, "Task" %>
            <%= f.radio_button :note_type, "event" %>
            <%= label :note_type_event, "Event" %>
            <%= f.radio_button :note_type, "note" %>
            <%= label :note_type_note, "Note" %>
        </div>
        <div>
            Due:
            <%= select_date Date.today, prefix: :due_date %>
        </div>
        <div>
            <%= check_box_tag :complete %>
            <%= label_tag(:complete, "Complete") %>
        </div>
        <%= f.submit "Add", class: 'btn btn-success' %>
    <% end %>
    <%= link_to "Back", notes_path %>
</div>

app/views/notes/show.html.erb
<div class="new">
    <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <h4><%= @note.due.month %>/<%= @note.due.day%>/<%=@note.due.year%></h4>


    <p id="content"><%= @note.content %></p>

    <%= link_to "Home", notes_path, class: 'btn btn-default' %>
    <%= link_to "Edit", edit_note_path(@note), class: 'btn btn-primary' %>
    <%= link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure you want to delete this note?"}, class: 'btn btn-danger'%>
</div>

app/views/notes/week.html.erb
<div class="week">
    <%= week_calendar number_of_weeks: 1 do |date|%>
        <strong ><%= date.day %></strong>
        <ul>
            <%@notes.each do |note|%>
                <%if note.due.year == date.year && note.due.month == date.month && note.due.day == date.day%>
                    <span class="<%=note.complete%>">
                    <li class="<%=note.note_type%>">
                        <%= link_to note.content, note_path(note) %>
                    </li>
                    </span>
                <% end %>
            <% end %>
        </ul>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="col-sm"><h1>Bullet Journal</h1></div>
<h3>Welcome to a Productive You</h3>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %><br>
        <%= f.label :email %>
        <%= f.text_field :email %><br>
        <%= f.label :password %>
        <%= f.password_field :password %><br>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %><br>
        <%= f.submit "Create User", class: 'btn btn-success' %>
    </div>

<% end %>